// AppDelegate.m — Boots the Mob BEAM on a background thread and presents
// a SwiftUI root view via UIHostingController (created by MobUIFactory).

#import <UIKit/UIKit.h>
#import <pthread.h>
#include <string.h>
#include "mob_beam.h"
#import "MobApp-Swift.h"  // generated by swiftc; exposes MobUIFactory

// Declared in mob_nif — delivers {:push_token, :ios, token} to the registered screen process.
extern void mob_send_push_token(const char* hex_token);

// Code-generated by MobDev.Plugin.IOSBootstrap at build time — registers each
// activated plugin's SwiftUI view with MobNativeViewRegistry.shared. Defined
// via Swift's @_cdecl in the generated file so it's a plain C symbol; safe to
// call before mob_init_ui() even when no plugins are activated (the function
// body is just empty in that case).
extern void mob_register_plugins(void);

// Exported by mob_nif: the orientation mask set by Mob.Device.lock_orientation/1
// (UIInterfaceOrientationMaskAll when unlocked).
extern UIInterfaceOrientationMask mob_locked_orientation_mask(void);

// Called from the thin `sigil_ios` C NIF. Snapshot paths are already copied
// into the app sandbox by Elixir; this only presents them.
int sigil_present_file(const char *path, const char *mode);

static UIViewController *sigil_root_vc(void) {
  for (UIScene *scene in [UIApplication sharedApplication].connectedScenes) {
    if ([scene isKindOfClass:[UIWindowScene class]]) {
      UIWindow *window = ((UIWindowScene *)scene).windows.firstObject;
      if (window.rootViewController)
        return window.rootViewController;
    }
  }
  return nil;
}

@interface SigilPresentDelegate : NSObject <UIDocumentInteractionControllerDelegate>
@property(nonatomic, strong) UIDocumentInteractionController *controller;
@end

@implementation SigilPresentDelegate
- (UIViewController *)documentInteractionControllerViewControllerForPreview:
    (UIDocumentInteractionController *)controller {
  return sigil_root_vc();
}
@end

static SigilPresentDelegate *g_present_delegate = nil;

static void sigil_present_open(NSURL *url) {
  UIViewController *root = sigil_root_vc();
  if (!root)
    return;
  g_present_delegate = [[SigilPresentDelegate alloc] init];
  UIDocumentInteractionController *ctrl =
      [UIDocumentInteractionController interactionControllerWithURL:url];
  ctrl.delegate = g_present_delegate;
  g_present_delegate.controller = ctrl;
  if (![ctrl presentPreviewAnimated:YES]) {
    [ctrl presentOpenInMenuFromRect:root.view.bounds inView:root.view animated:YES];
  }
}

static void sigil_present_share(NSURL *url) {
  UIViewController *root = sigil_root_vc();
  if (!root)
    return;
  UIActivityViewController *vc =
      [[UIActivityViewController alloc] initWithActivityItems:@[ url ]
                                        applicationActivities:nil];
  if (vc.popoverPresentationController) {
    vc.popoverPresentationController.sourceView = root.view;
    CGRect r = root.view.bounds;
    vc.popoverPresentationController.sourceRect =
        CGRectMake(CGRectGetMidX(r), CGRectGetMidY(r), 0, 0);
  }
  [root presentViewController:vc animated:YES completion:nil];
}

int sigil_present_file(const char *path, const char *mode) {
  if (!path || path[0] != '/')
    return -1;
  NSString *nsPath = [NSString stringWithUTF8String:path];
  if (!nsPath || ![[NSFileManager defaultManager] fileExistsAtPath:nsPath])
    return -1;
  NSURL *url = [NSURL fileURLWithPath:nsPath];
  BOOL share = mode && strcmp(mode, "share") == 0;
  dispatch_async(dispatch_get_main_queue(), ^{
    if (share)
      sigil_present_share(url);
    else
      sigil_present_open(url);
  });
  return 0;
}

static void* beam_thread(void* arg) {
    mob_start_beam((const char*)arg);
    return NULL;
}

@interface AppDelegate : UIResponder <UIApplicationDelegate>
@end

@implementation AppDelegate

// Xcode 27 requires scene-based startup — window creation and BEAM boot moved
// to SceneDelegate below. This stays a no-op rather than being dropped
// entirely for parity with older AppDelegate-only expectations.
- (BOOL)application:(UIApplication*)app
    didFinishLaunchingWithOptions:(NSDictionary*)opts {
    return YES;
}

// Holds an orientation lock. UIKit consults this window-level method in
// preference to the root view controller's -supportedInterfaceOrientations, so
// the rotation Mob.Device.lock_orientation/1 requests via requestGeometryUpdate
// actually sticks (and unlock_orientation/0 returns ...MaskAll = follow sensor).
- (UIInterfaceOrientationMask)application:(UIApplication*)app
    supportedInterfaceOrientationsForWindow:(UIWindow*)window {
    return mob_locked_orientation_mask();
}

- (void)application:(UIApplication*)app
    didRegisterForRemoteNotificationsWithDeviceToken:(NSData*)deviceToken {
    // Convert token bytes to hex string and deliver to Elixir via NIF.
    NSMutableString* hex = [NSMutableString stringWithCapacity:deviceToken.length * 2];
    const unsigned char* bytes = (const unsigned char*)deviceToken.bytes;
    for (NSUInteger i = 0; i < deviceToken.length; i++) {
        [hex appendFormat:@"%02x", bytes[i]];
    }
    mob_send_push_token([hex UTF8String]);
}

- (void)application:(UIApplication*)app
    didFailToRegisterForRemoteNotificationsWithError:(NSError*)error {
    NSLog(@"[Mob] Failed to register for remote notifications: %@", error);
}

@end

// SceneDelegate — Xcode 27 requires scene-based app startup, so window
// creation and the BEAM boot that used to live in
// AppDelegate.didFinishLaunchingWithOptions: move here instead.
@interface SceneDelegate : UIResponder <UIWindowSceneDelegate>
@property (strong, nonatomic) UIWindow *window;
@end

@implementation SceneDelegate

- (void)scene:(UIScene*)scene
    willConnectToSession:(UISceneSession*)session
    options:(UISceneConnectionOptions*)connectionOptions {
    if (![scene isKindOfClass:[UIWindowScene class]]) {
        return;
    }

    self.window = [[UIWindow alloc] initWithWindowScene:(UIWindowScene*)scene];
    self.window.rootViewController = [MobUIFactory makeRootViewController];
    [self.window makeKeyAndVisible];

    // willConnectToSession: can fire more than once per process — iOS may
    // disconnect the scene (memory pressure, backgrounding) and later
    // reconnect it without relaunching the app. The window above is rebuilt
    // every time, but the plugin registry and the BEAM must boot exactly
    // once per process: a second erl_start in the same process is fatal, and
    // nothing in mob's native layer guards against it.
    static dispatch_once_t mob_boot_once;
    dispatch_once(&mob_boot_once, ^{
        // Must run before mob_init_ui() so the registry has every plugin view
        // factory in place by the time the BEAM mounts its first screen.
        mob_register_plugins();

        mob_init_ui();

        extern const char* mob_app_module(void);
        pthread_t t;
        pthread_create(&t, NULL, beam_thread, (void*)mob_app_module());
        pthread_detach(t);
    });
}

@end

int main(int argc, char* argv[]) {
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, @"AppDelegate");
    }
}
