// beam_main.m — Generated by mix mob.new.
// Edit APP_MODULE to change the Elixir app module name.

#define APP_MODULE "sigil_probe"

// Returns the app module name to AppDelegate.m (avoids a shared header).
const char* mob_app_module(void) {
    return APP_MODULE;
}
