// Generated by mob_dev (MobDev.NativeBuild) — do not edit.
// A plugin bridge class implements this to receive the host Activity from
// MobPluginBootstrap.registerAll, right after register().
package io.mob.plugin

import android.app.Activity

interface MobActivityAware {
    fun setActivity(activity: Activity)
}
