// GENERATED by mob_dev — do not edit. Stable cross-package seam for
// notification-delivery state: host delivery code (MobFirebaseService /
// MainActivity / NotificationReceiver, app package) and the mob_notify
// plugin bridge (io.mob.notify) both use it; neither can reference the
// other's generated package directly.
package io.mob.plugin

object MobNotifyHub {
    // Local-notification channel id — the host NotificationReceiver posts
    // to it; the plugin's notify_schedule creates it.
    const val CHANNEL_ID = "mob_notifications"

    // The screen process registered via MobNotify.register_push/1. Host
    // delivery paths (FCM foreground push, notification tap) send to it
    // via core's nativeDeliver* thunks; 0 = no screen registered.
    @Volatile @JvmStatic var notifyPid: Long = 0

    // FCM token that refreshed while no screen was registered; the
    // plugin's notify_register_push drains it.
    @Volatile @JvmStatic var pendingToken: String? = null
}
