import Config

# Configure your database
config :sigil, Sigil.Repo,
  database: Path.expand("../sigil_dev.db", __DIR__),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sigil, SigilWeb.Endpoint,
  # Bind all interfaces in Amp orbs so portal health checks can reach $PORT.
  # Keep loopback-only on a normal local machine.
  http: [ip: if(System.get_env("AMP_ORB") == "1", do: {0, 0, 0, 0}, else: {127, 0, 0, 1})],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base:
    System.get_env("SECRET_KEY_BASE") ||
      "4q06/NhjIcyS+rVbrFZwpEUfBdrXzc70mUo4pQwFco7LB/q/QE9B6xkPp0hTMlfO",
  watchers: [
    node: ["build_assets.mjs", "--watch", cd: Path.expand("..", __DIR__)]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :sigil, SigilWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/sigil_web/router\.ex$"E,
      ~r"lib/sigil_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :sigil, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Observational Memory — automatic context capture + future LLM Observer/Reflector
# Set enabled: true to activate (P0: zero-LLM middleware observations)
config :sigil, :observational_memory,
  enabled: false,

  # P0 — zero-LLM automatic observations via middleware hooks
  observation: [
    max_recent_context: 5
  ],

  # P1 — LLM Observer (extracts structured observations from raw events)
  # Uses a cheap/fast model to minimise cost
  observer: [
    model: "claude-haiku-4-5-20251001",
    provider: nil,
    model_settings: [
      temperature: 0.3,
      max_output_tokens: 4000
    ],
    message_tokens: 30_000,
    buffer_tokens: 10_000,
    instruction: nil
  ],

  # P2 — LLM Reflector (compresses observations → long-term engrams)
  reflector: [
    model: "claude-haiku-4-5-20251001",
    provider: nil,
    model_settings: [
      temperature: 0,
      max_output_tokens: 8000
    ],
    observation_tokens: 40_000
  ]
