// beam_jni.c — JNI entry points for SigilProbe.
// Generated by mix mob.new. Edit the two defines below; do not touch the rest.

#include <jni.h>
#include "mob_beam.h"

#define BRIDGE_CLASS  "com/example/sigil_probe/MobBridge"
#define APP_MODULE    "sigil_probe"

JavaVM* g_jvm      = NULL;
jobject g_activity = NULL;

JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void* reserved) {
    g_jvm = vm;
    JNIEnv* env;
    (*vm)->GetEnv(vm, (void**)&env, JNI_VERSION_1_6);
    mob_ui_cache_class(env, BRIDGE_CLASS);
    return JNI_VERSION_1_6;
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MainActivity_nativeSetActivity(JNIEnv* env, jobject thiz, jobject activity) {
    mob_init_bridge(env, activity);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MainActivity_nativeStartBeam(JNIEnv* env, jobject thiz) {
    mob_start_beam(APP_MODULE);
}

// Called from MainActivity.onConfigurationChanged on a rotation. Forwards the
// new orientation string to the BEAM. mob_send_orientation_changed is exported
// by mob_nif.zig; declared here in case it's not in mob_beam.h.
extern void mob_send_orientation_changed(const char* orient);

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MainActivity_nativeNotifyOrientation(JNIEnv* env, jobject thiz, jstring orient) {
    const char* utf8 = (*env)->GetStringUTFChars(env, orient, NULL);
    mob_send_orientation_changed(utf8);
    (*env)->ReleaseStringUTFChars(env, orient, utf8);
}

// Called from MainActivity's ConnectivityManager.NetworkCallback when the active
// network path changes. Forwards online/transport/expensive to the BEAM
// (Mob.Device.network_state/0 + :network subscribers).
// mob_send_connectivity_changed is exported by mob_nif.zig.
extern void mob_send_connectivity_changed(int online, const char* transport, int expensive,
    int validated);

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MainActivity_nativeNotifyConnectivity(JNIEnv* env, jobject thiz,
    jboolean online, jstring transport, jboolean expensive, jboolean validated) {
    // utf8 is NULL if transport is null OR GetStringUTFChars failed (OOM); pass
    // "none" in that case and only release what we actually acquired.
    const char* utf8 = transport ? (*env)->GetStringUTFChars(env, transport, NULL) : NULL;
    mob_send_connectivity_changed(online ? 1 : 0, utf8 ? utf8 : "none", expensive ? 1 : 0,
        validated ? 1 : 0);
    if (utf8) (*env)->ReleaseStringUTFChars(env, transport, utf8);
}

// Called from MobBridge.nativeSendTap(handle) in Kotlin when a button is tapped.
JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendTap(JNIEnv* env, jclass cls, jint handle) {
    mob_send_tap((int)handle);
}

// Called from MobBridge.nativeSendLongPress(handle) / nativeSendDoubleTap.
// The senders have existed on this platform all along; what was missing was any
// Kotlin path to them, so `on_long_press` and `on_double_tap` were registered by
// the renderer, carried in the JSON, and then silently never fired (MOB-138).
JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendLongPress(JNIEnv* env, jclass cls, jint handle) {
    mob_send_long_press((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendDoubleTap(JNIEnv* env, jclass cls, jint handle) {
    mob_send_double_tap((int)handle);
}

// Swipe. nativeSendSwipe carries the direction string through to
// mob_send_swipe_with_direction, which emits {:swipe, tag, direction_atom};
// the four fixed senders emit {:swipe_left, tag} and friends. A node can
// declare both and iOS delivers both, so Kotlin calls both.
JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendSwipe(JNIEnv* env, jclass cls, jint handle,
                                                  jstring direction) {
    const char* dir = (*env)->GetStringUTFChars(env, direction, NULL);
    if (dir == NULL) return;
    mob_send_swipe_with_direction((int)handle, dir);
    (*env)->ReleaseStringUTFChars(env, direction, dir);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendSwipeLeft(JNIEnv* env, jclass cls, jint handle) {
    mob_send_swipe_left((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendSwipeRight(JNIEnv* env, jclass cls, jint handle) {
    mob_send_swipe_right((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendSwipeUp(JNIEnv* env, jclass cls, jint handle) {
    mob_send_swipe_up((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendSwipeDown(JNIEnv* env, jclass cls, jint handle) {
    mob_send_swipe_down((int)handle);
}

// Scroll family. mob_send_scroll applies the per-handle throttle and delta
// threshold before it reaches the BEAM, so forwarding every observed sample
// here is intentional — the gating lives native-side, not in Kotlin. The
// per-handler scroll_config/drag_config props ARE honoured: the composition
// calls mob_set_throttle_config (see nativeSetThrottleConfig below), and the
// compiled-in defaults apply only where a handler asked for nothing (MOB-134).
JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendScroll(JNIEnv* env, jclass cls, jint handle,
                                                   jdouble x, jdouble y, jdouble dx, jdouble dy,
                                                   jdouble vx, jdouble vy, jstring phase) {
    const char* ph = (*env)->GetStringUTFChars(env, phase, NULL);
    if (ph == NULL) return;
    mob_send_scroll((int)handle, (double)x, (double)y, (double)dx, (double)dy,
                    (double)vx, (double)vy, ph);
    (*env)->ReleaseStringUTFChars(env, phase, ph);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendScrollBegan(JNIEnv* env, jclass cls, jint handle) {
    mob_send_scroll_began((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendScrollEnded(JNIEnv* env, jclass cls, jint handle) {
    mob_send_scroll_ended((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendScrollSettled(JNIEnv* env, jclass cls, jint handle) {
    mob_send_scroll_settled((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendTopReached(JNIEnv* env, jclass cls, jint handle) {
    mob_send_top_reached((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendScrolledPast(JNIEnv* env, jclass cls, jint handle) {
    mob_send_scrolled_past((int)handle);
}

// Per-handle throttle config (MOB-134). Re-sent on every render because
// clear_taps zeroes the throttle state each frame and the handler is
// re-registered under a new handle. Resolving against the active table is
// correct on this platform: nif_set_root swaps before Kotlin composes.
JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSetThrottleConfig(JNIEnv* env, jclass cls, jint handle,
                                                          jint throttle_ms, jint debounce_ms,
                                                          jdouble delta_threshold, jint leading,
                                                          jint trailing) {
    mob_set_throttle_config((int)handle, (int)throttle_ms, (int)debounce_ms,
                            (double)delta_threshold, (int)leading, (int)trailing);
}

// Canvas drag. Coordinates arrive already converted to dp by the Kotlin side,
// matching the canvas's own coordinate space and iOS's points.
JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendDrag(JNIEnv* env, jclass cls, jint handle,
                                                 jdouble x, jdouble y, jdouble dx, jdouble dy,
                                                 jstring phase) {
    const char* ph = (*env)->GetStringUTFChars(env, phase, NULL);
    if (ph == NULL) return;
    mob_send_drag((int)handle, (double)x, (double)y, (double)dx, (double)dy, ph);
    (*env)->ReleaseStringUTFChars(env, phase, ph);
}

// Called from MobBridge.nativeSendDismiss(handle) when a sheet is dismissed.
// Distinct from nativeSendTap because Mob.UI.sheet/2's :on_dismiss is
// documented as {:dismiss, tag} and iOS delivers exactly that — routing it
// through the tap sender delivered {:tap, tag} instead, which no screen
// written to the contract matches (MOB-104).
JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendDismiss(JNIEnv* env, jclass cls, jint handle) {
    mob_send_dismiss((int)handle);
}

// Called from MobBridge.nativeSendChangeStr/Bool/Float when an input widget changes.
JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendChangeStr(JNIEnv* env, jclass cls, jint handle, jstring value) {
    const char* utf8 = (*env)->GetStringUTFChars(env, value, NULL);
    mob_send_change_str((int)handle, utf8);
    (*env)->ReleaseStringUTFChars(env, value, utf8);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendChangeBool(JNIEnv* env, jclass cls, jint handle, jboolean value) {
    mob_send_change_bool((int)handle, (int)value);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendChangeFloat(JNIEnv* env, jclass cls, jint handle, jfloat value) {
    mob_send_change_float((int)handle, (double)value);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendFocus(JNIEnv* env, jclass cls, jint handle) {
    mob_send_focus((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendBlur(JNIEnv* env, jclass cls, jint handle) {
    mob_send_blur((int)handle);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSendSubmit(JNIEnv* env, jclass cls, jint handle) {
    mob_send_submit((int)handle);
}

// Called from MobBridge.nativeHandleBack() when the Android back gesture fires.
JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeHandleBack(JNIEnv* env, jclass cls) {
    mob_handle_back();
}

// Called from MobBridge.notifyColorSchemeChanged when MainActivity's
// onConfigurationChanged sees a uiMode flip. `scheme` is "light" or "dark".
JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeNotifyColorScheme(JNIEnv* env, jclass cls,
    jstring scheme) {
    if (!scheme) return;
    const char* utf8 = (*env)->GetStringUTFChars(env, scheme, NULL);
    if (utf8) {
        mob_send_color_scheme_changed(utf8);
        (*env)->ReleaseStringUTFChars(env, scheme, utf8);
    }
}

// ── Device capability result delivery ────────────────────────────────────
// Called from MobBridge when async results are ready.

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverAtom2(JNIEnv* env, jclass cls,
    jlong pid, jstring a1, jstring a2) {
    const char* ca1 = (*env)->GetStringUTFChars(env, a1, NULL);
    const char* ca2 = (*env)->GetStringUTFChars(env, a2, NULL);
    mob_deliver_atom2(pid, ca1, ca2);
    (*env)->ReleaseStringUTFChars(env, a1, ca1);
    (*env)->ReleaseStringUTFChars(env, a2, ca2);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverAtom3(JNIEnv* env, jclass cls,
    jlong pid, jstring a1, jstring a2, jstring a3) {
    const char* ca1 = (*env)->GetStringUTFChars(env, a1, NULL);
    const char* ca2 = (*env)->GetStringUTFChars(env, a2, NULL);
    const char* ca3 = (*env)->GetStringUTFChars(env, a3, NULL);
    mob_deliver_atom3(pid, ca1, ca2, ca3);
    (*env)->ReleaseStringUTFChars(env, a1, ca1);
    (*env)->ReleaseStringUTFChars(env, a2, ca2);
    (*env)->ReleaseStringUTFChars(env, a3, ca3);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverMotion(JNIEnv* env, jclass cls,
    jlong pid, jdouble ax, jdouble ay, jdouble az,
    jdouble gx, jdouble gy, jdouble gz, jlong ts) {
    mob_deliver_motion(pid, ax, ay, az, gx, gy, gz, (long long)ts);
}

// mob_deliver_motion_mag is exported by mob_nif.zig; declared here in case the
// installed mob_beam.h predates the magnetometer/heading delivery function.
extern void mob_deliver_motion_mag(jlong pid, double ax, double ay, double az,
                                   double gx, double gy, double gz, double mx,
                                   double my, double mz, double heading,
                                   long long ts);

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverMotionMag(JNIEnv* env, jclass cls,
    jlong pid, jdouble ax, jdouble ay, jdouble az,
    jdouble gx, jdouble gy, jdouble gz,
    jdouble mx, jdouble my, jdouble mz, jdouble heading, jlong ts) {
    mob_deliver_motion_mag(pid, ax, ay, az, gx, gy, gz, mx, my, mz, heading,
                           (long long)ts);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverFileResult(JNIEnv* env, jclass cls,
    jlong pid, jstring event, jstring sub, jstring json_items) {
    const char* ce  = (*env)->GetStringUTFChars(env, event, NULL);
    const char* cs  = (*env)->GetStringUTFChars(env, sub,   NULL);
    const char* cj  = json_items ? (*env)->GetStringUTFChars(env, json_items, NULL) : NULL;
    mob_deliver_file_result(pid, ce, cs, cj);
    (*env)->ReleaseStringUTFChars(env, event, ce);
    (*env)->ReleaseStringUTFChars(env, sub,   cs);
    if (cj) (*env)->ReleaseStringUTFChars(env, json_items, cj);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverPushToken(JNIEnv* env, jclass cls,
    jlong pid, jstring token) {
    const char* ct = (*env)->GetStringUTFChars(env, token, NULL);
    mob_deliver_push_token(pid, ct);
    (*env)->ReleaseStringUTFChars(env, token, ct);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverNotification(JNIEnv* env, jclass cls,
    jlong pid, jstring json) {
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_deliver_notification(pid, cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeSetLaunchNotification(JNIEnv* env, jclass cls,
    jstring json) {
    if (!json) { mob_set_launch_notification(NULL); return; }
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_set_launch_notification(cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverWebViewMessage(JNIEnv* env, jclass cls,
    jlong pid, jstring json) {
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_deliver_webview_message(pid, cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverWebViewBlocked(JNIEnv* env, jclass cls,
    jlong pid, jstring url) {
    const char* cu = (*env)->GetStringUTFChars(env, url, NULL);
    mob_deliver_webview_blocked(pid, cu);
    (*env)->ReleaseStringUTFChars(env, url, cu);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverAlertAction(JNIEnv* env, jclass cls,
    jstring action) {
    const char* ca = (*env)->GetStringUTFChars(env, action, NULL);
    mob_deliver_alert_action(ca);
    (*env)->ReleaseStringUTFChars(env, action, ca);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverComponentEvent(JNIEnv* env, jclass cls,
    jint handle, jstring event, jstring payload_json) {
    const char* ce = (*env)->GetStringUTFChars(env, event,        NULL);
    const char* cj = (*env)->GetStringUTFChars(env, payload_json, NULL);
    mob_send_component_event((int)handle, ce, cj);
    (*env)->ReleaseStringUTFChars(env, event,        ce);
    (*env)->ReleaseStringUTFChars(env, payload_json, cj);
}

// ── Mob.Peripheral.VendorUsb delivery thunks ─────────────────────────────────
// Called from MobBridge's USB code when Android USB host events fire.
// See lib/mob/peripheral/vendor_usb.ex for the public message envelope shape.

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverVendorUsbDevices(JNIEnv* env, jclass cls,
    jlong pid, jstring json) {
    const char* cj = (*env)->GetStringUTFChars(env, json, NULL);
    mob_deliver_vendor_usb_devices(pid, cj);
    (*env)->ReleaseStringUTFChars(env, json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverVendorUsbPermission(JNIEnv* env, jclass cls,
    jlong pid, jboolean granted, jstring device_json) {
    const char* cj = (*env)->GetStringUTFChars(env, device_json, NULL);
    mob_deliver_vendor_usb_permission(pid, granted ? 1 : 0, cj);
    (*env)->ReleaseStringUTFChars(env, device_json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverVendorUsbOpened(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jstring device_json) {
    const char* cj = (*env)->GetStringUTFChars(env, device_json, NULL);
    mob_deliver_vendor_usb_opened(pid, (int)session_id, cj);
    (*env)->ReleaseStringUTFChars(env, device_json, cj);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverVendorUsbData(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jbyteArray bytes, jint len) {
    if (!bytes || len <= 0) {
        mob_deliver_vendor_usb_data(pid, (int)session_id, NULL, 0);
        return;
    }
    jbyte* buf = (*env)->GetByteArrayElements(env, bytes, NULL);
    if (buf) {
        mob_deliver_vendor_usb_data(pid, (int)session_id, (const uint8_t*)buf, (size_t)len);
        (*env)->ReleaseByteArrayElements(env, bytes, buf, JNI_ABORT);
    }
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverVendorUsbWriteComplete(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jint bytes_written) {
    mob_deliver_vendor_usb_write_complete(pid, (int)session_id, (int)bytes_written);
}

JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeDeliverVendorUsbEvent(JNIEnv* env, jclass cls,
    jlong pid, jint session_id, jstring tag, jstring reason) {
    const char* ct = (*env)->GetStringUTFChars(env, tag, NULL);
    const char* cr = reason ? (*env)->GetStringUTFChars(env, reason, NULL) : NULL;
    mob_deliver_vendor_usb_event(pid, (int)session_id, ct, cr);
    (*env)->ReleaseStringUTFChars(env, tag, ct);
    if (cr) (*env)->ReleaseStringUTFChars(env, reason, cr);
}

// Stop on the FGS notification must cancel Runner work, not only the service.
JNIEXPORT void JNICALL
Java_com_example_sigil_1probe_MobBridge_nativeCancelRuns(JNIEnv* env, jclass cls) {
    (void)env;
    (void)cls;
    mob_deliver_alert_action("cancel_all_runs");
}
