// Generated by mob_dev (MobDev.NativeBuild) — do not edit.
// A plugin bridge class implements this to supply the Android permission
// strings for a capability; MobPluginBootstrap collects providers at
// registerAll and core MobBridge.request_permission consults them.
package io.mob.plugin

interface MobPermissionProvider {
    // Return the Android permission strings for `cap`, or null if this
    // provider does not handle the capability.
    fun permissionsFor(cap: String): Array<String>?
}
