// Generated by mob_dev (MobDev.NativeBuild) — do not edit.
// Registers explicitly opted-in ui_components Compose factories, then calls
// each activated plugin's bridge-class register() and hands the Activity to
// bridges implementing MobActivityAware. Bridge-owned factories run last.
// Invoked from MainActivity.onCreate as registerAll(this), before
// setContent renders anything.
package io.mob.plugin

import android.app.Activity

object MobPluginBootstrap {
    private val permissionProviders = mutableListOf<MobPermissionProvider>()

    @JvmStatic
    fun registerAll(activity: Activity) {}

    // Returns the first plugin-supplied Android permission mapping for `cap`,
    // or null if no activated plugin provides this capability. Core
    // MobBridge.request_permission consults this in its `else` branch.
    @JvmStatic
    fun permissionsFor(cap: String): Array<String>? {
        for (provider in permissionProviders) {
            val perms = provider.permissionsFor(cap)
            if (perms != null) return perms
        }
        return null
    }
}
